### PR TITLE
Um, anyone using adfly will be here.

### PR DESCRIPTION
**Pull request by JordanB-1337**

### CODE REVIEW

**Comment by haylinmoore** [comment]
Umm that is a beta page

**Comment by JordanB-1337** [comment]
What does that mean?

**Comment by JordanB-1337** [comment]
Well I know what beta means but what does that mean for its content?

**Comment by herohamp** [comment]
i

**Comment by haylinmoore** [comment]
it just has no content yet

**Comment by HittmanA** [comment]
Merge it anyway for now

**Comment by haylinmoore** [comment]
uggg

**Pull request merged**
